version: "3"
services:
    web:
        build: .
        container_name: api
        ports:
            - "8080:80"
        depends_on:
            - sqlserver
        restart: always

    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: sqlserver
        environment:
            SA_PASSWORD: "Toochukwu@77"
            ACCEPT_EULA: "Y"
        expose:
            - "1433"
        # You don't need this. I will have to explain why over call
        # ports:
        #     - "1445:1433" 